title: GraceTHD-MOD
description: Documents préconisant un Modèle d'Organisation des Données applicable en relation avec le modèle de données GraceTHD
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect
github:
  zip_url: 'https://github.com/GraceTHD-community/GraceTHD-MOD/zipball/master'
  tar_url: 'https://github.com/GraceTHD-community/GraceTHD-MOD/tarball/master'
gems:
  - jekyll-mentions
